config/routes.rb
Rails.application.routes.draw do
  resources :it_assets

end

app/models/it_asset.rb
class ItAsset
  include Neo4j::ActiveNode
  property :category, type: String
  property :name, type: String, constraint: :unique

  has_many :out, :needs, type: :NEEDS, model_class: :ItAsset

  IT_ASSET_CATEGORIES = %w[data_center networking hardware hosting os_platform sw_platfrom it_facing_service user_facing_service]

  validates :category, :presence => true, :inclusion=> { :in => IT_ASSET_CATEGORIES }
  validates :name, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/it_assets_controller.rb
class ItAssetsController < ApplicationController
  before_action :set_it_asset, only: [:show, :edit, :update, :destroy]

  # GET /it_assets
  # GET /it_assets.json
  def index
    @it_assets = ItAsset.all.with_associations(:needs)
  end

  # GET /it_assets/1
  # GET /it_assets/1.json
  def show
  end

  # GET /it_assets/new
  def new
    @it_asset = ItAsset.new
  end

  # GET /it_assets/1/edit
  def edit
  end

  # POST /it_assets
  # POST /it_assets.json
  def create
    @it_asset = ItAsset.new(it_asset_params)

    respond_to do |format|
      if @it_asset.save
        format.html { redirect_to @it_asset, notice: 'It asset was successfully created.' }
        format.json { render :show, status: :created, location: @it_asset }
      else
        format.html { render :new }
        format.json { render json: @it_asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /it_assets/1
  # PATCH/PUT /it_assets/1.json
  def update
    respond_to do |format|
      if @it_asset.update(it_asset_params)
        format.html { redirect_to @it_asset, notice: 'It asset was successfully updated.' }
        format.json { render :show, status: :ok, location: @it_asset }
      else
        format.html { render :edit }
        format.json { render json: @it_asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /it_assets/1
  # DELETE /it_assets/1.json
  def destroy
    @it_asset.destroy
    respond_to do |format|
      format.html { redirect_to it_assets_url, notice: 'It asset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_it_asset
      @it_asset = ItAsset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def it_asset_params
      params.require(:it_asset).permit(:category, :name, :need_ids => [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/it_assets_helper.rb
module ItAssetsHelper
end

app/views/it_assets/_form.html.erb
<%= form_for(@it_asset) do |f| %>
  <% if @it_asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@it_asset.errors.count, "error") %> prohibited this it_asset from being saved:</h2>

      <ul>
      <% @it_asset.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.select( :category, ItAsset::IT_ASSET_CATEGORIES, include_blank: true ) %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label 'Depends On' %><br>
    <%= f.select :need_ids, options_from_collection_for_select(ItAsset.order(:name), :id, :name, @it_asset.needs.map(&:id)), {include_blank: true}, {multiple: true, size: 10} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/it_assets/edit.html.erb
<h1>Editing It Asset</h1>

<%= render 'form' %>

<%= link_to 'Show', @it_asset %> |
<%= link_to 'Back', it_assets_path %>

app/views/it_assets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing It Assets</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Name</th>
      <th>Needs</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @it_assets.each do |it_asset| %>
      <tr>
        <td><%= it_asset.category %></td>
        <td><%= it_asset.name %></td>
        <td>
          <ul>
            <% it_asset.needs.each do |need| %>
              <li><%= link_to need.name, need %></li>
            <% end %>
          </ul>
        </td>
        <td><%= link_to 'Show', it_asset %></td>
        <td><%= link_to 'Edit', edit_it_asset_path(it_asset) %></td>
        <td><%= link_to 'Destroy', it_asset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New It asset', new_it_asset_path %>

app/views/it_assets/new.html.erb
<h1>New It Asset</h1>

<%= render 'form' %>

<%= link_to 'Back', it_assets_path %>

app/views/it_assets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @it_asset.category %>
</p>

<p>
  <strong>Name:</strong>
  <%= @it_asset.name %>
</p>

<p>
  <strong>Needs:</strong>
  <%= @it_asset.needs.map(&:name).to_sentence %>
  <br>
  <ul>
    <% @it_asset.needs.each do |need| %>
      <li><%= link_to need.name, need %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_it_asset_path(@it_asset) %> |
<%= link_to 'Back', it_assets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ItNeeds</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>